version: '3.8'

services:
  api:
    restart: always
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://fastapi:fastapi@db:5432/fastapi
    depends_on:
      - db


  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

volumes:
  postgres_data: