name: api-tests workflow

on:
  push:
    branches:
      - backend_develop
      - main
  pull:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r api/requirements.txt
    - name: Test with flake8
      run: |
        cd api/app/
        python -m flake8